# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the TypeScript code
RUN npm run build

# Command to run the MCP server via stdio
CMD [ "node", "dist/server.js" ] 